name: release
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: src/github.com/fraima/nexus-public

      - name: Run the Maven verify phase
        run: |
          pwd \
          ls -al \


        working-directory: src/github.com/fraima/nexus-public

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: src/github.com/fraima/nexus-public/_output/releases/*
          bodyFile: src/github.com/fraima/nexus-public/release-notes.md

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: src/github.com/fraima/nexus-public/_output
